apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: test-golang-pipeline-run-
  namespace: default
spec:
  params:
  - name: git_url
    value: https://github.com/marco210/test9000.git
  - name: imageTag
    value: v1
  - name: imageUrl
    value: marco210/test2-pipe
  pipelineRef:
    name: test-golang-pipeline
  workspaces:
  - name: test-ws
    persistentVolumeClaim:
      claimName: tekton-pvc
  - name: docker-reg-creds
    secret:
      secretName: docker-creds
status: {}
